### ISSUE TITLE
babelHelpers is not defined

### ISSUE THREAD

**Issue by ludekstepan** [router5/redux-router5#10]
Hi,

I'm trying to setup the Router5 with my Redux devstack, unfortunately I get errors while creating the reducer:

```
router5Reducer.js:30 Uncaught ReferenceError: babelHelpers is not defined(…)
router5Reducer @ router5Reducer.js:30
...
```

I think the problem is caused by:
https://github.com/router5/redux-router5/blob/v4.2.2/dist/es/lib/router5Reducer.js#L30

**Comment by troch** [comment]
Are you using webpack 2?

**Comment by ludekstepan** [comment]
Yes, feel free to check my setup: https://github.com/ludekstepan/ts-boilerplate/tree/router5

**Comment by troch** [comment]
I just released 4.2.2 today and added in `package.json` the "module" key (consumed by webpack). Those files are generated using a rollup preset (`babel-preset-es2015-rollup`) which is doing a little more than I thought (`babelHelpers`). That's where the problem comes from. I'll fix it tonight, you can use 4.2.1 in the mean time.

**Comment by ludekstepan** [comment]
Great, 4.2.1 works just fine. I'll retest once you release a new version. Thanks!

**Comment by troch** [comment]
4.2.3 released. Thanks for raising this issue.

**Comment by ludekstepan** [comment]
Works like a charm. Thank you very much!
