### ISSUE TITLE
Router initial state

### ISSUE THREAD

**Issue by klimashkin** [router5/redux-router5#4]
Am I right that `startPathOrState` argument of `.start()` is not needed if `redux-router5` is used and initial state `{ router: { route: state }}` is passed to store creation function?
If so, could you clarify how `state` should look like in this case?

**Comment by troch** [comment]
Depends, supplying a `startPathOrState` is better since the router will emit events which will end up populating your store anyway. If you are supplying a start state, the router is not performing an initial route matching / transition: so it is best in case of an universal application you are hydrating in the browser. `state` needs to have a name and params properties.

**Comment by klimashkin** [comment]
I see, so if I render completely new state, for example, for each http request on server, 'startPathOrState' must be used.
But if I want to restore last state, for instance if user closed tab and before closing redux state was saved to localStorage, then restore this tab, I can just apply object from localStorage to initial redux state with router property.

**Comment by troch** [comment]
Those two cases sound similar to me. Actually what I do myself is I do both. When pre-rendering on the server, I end-up with 3 pieces of state: the store state, the router state and the statically rendered markup. In the browser I then start the router with its start state and create the store with its state.

Using `startStateOrPath` allows (only if it is a state, not a path) the router to skip the transition and for example not re-trigger some data loading (which could already be in your store). So I would say: do both
